spring:
    application:
        name: Visualiza-exames
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:h2:mem:sistemaa;DB_CLOSE_DELAY=-1
        name:
        username: sistemaA
        password:
    h2:
        console:
            enabled: true
    jpa:
        database: H2
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
server:
    port: 8080
